services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend

  api:
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: sh -c "./wait-for-it.sh mongodb:${DATABASE_PORT} -- npm run seed:prod && npm run start:prod"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - backend
    environment:
      - NODE_ENV=production

volumes:
  mongodb_data_container:

networks:
  backend:
    driver: bridge
